# SETUP YAML file for Grid-to-grid demo - February 2020

EVA:
  work_radius: 0.6    # Eva's workspace radius [m] - DO NOT CHANGE THIS PARAMETER
  base_plate: 0.132   # Eva's base-plate dimension [m] - DO NOT CHANGE THIS PARAMETER
  comm:
    host: "0.0.0.0"   # USER DEFINED
    token: "abcd1234" # USER DEFINED
  end_effector:
    payload: 0        # payload [kg] - USER DEFINED
    length: 80        # length of tool [mm] - USER DEFINED
    offset:           # ee offset in ee-frame  [m] - USER DEFINED
      - 0
      - 0
      - 0
  hover_height: 0.1   # elevation of idle z axis wrt to the object [m] - USER DEFINED
  home:               # joints for home position [rad] - USER DEFINED
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0

grids:
  names:          # DO NOT CHANGE THESE PARAMETERS
    - 'A'
    - 'B'
  names_verbose:  # object names - USER DEFINED
    A: 'Origin'
    B: 'Target'
  row:            # grid rows, [#] - USER DEFINED
    A: 0
    B: 0
  col:            # grid cols, [#] - USER DEFINED
    A: 0
    B: 0
  row_pitch:      # rows pitch [mm] - USER DEFINED
    A: 0
    B: 0
  col_pitch:      # cols pitch [mm] - USER DEFINED
    A: 0
    B: 0
  x0:             # grid angle, x [mm] - USER DEFINED
    A: 0
    B: 0
  y0:             # grid angle, y [mm] - USER DEFINED
    A: 0
    B: 0
  angle:          # grid orientation, [deg] - USER DEFINED
    A: 0
    B: 0
  angle_pickup:   # additional pick-up angle, [deg] - USER DEFINED
    A: 0
    B: 0
  surface:        # surf height of grid, [mm] - USER DEFINED
    A: 0
    B: 0
  object:         # object height, [mm] - USER DEFINED
    A: 0
    B: 0
  guess:
    A:            # joints grid guess, pick-up [rad] - USER DEFINED
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    B:            # joints guess, drop-off [rad] - USER DEFINED
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0