# SETUP YAML file for Grid-to-grid demo

EVA:
  work_radius: 0.6    # Eva's workspace radius [m] - DO NOT CHANGE THIS PARAMETER
  base_plate: 0.132   # Eva's base-plate dimension [m] - DO NOT CHANGE THIS PARAMETER
  comm:
    host: "0.0.0.0"   # USER DEFINED
    token: "abcd1234" # USER DEFINED
  end_effector:
    payload: 0        # payload [kg] - USER DEFINED
    length: 80        # length of tool [mm] - USER DEFINED
    offset:           # ee offset in ee-frame  [m] - USER DEFINED
      - 0
      - 0
      - 0
  hover_height: 0.1   # elevation of idle z axis wrt to the object [m] - USER DEFINED
  home:               # joints for home position [rad] - USER DEFINED
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0

grids:
  names:          # internal names - DO NOT CHANGE
    - 'A'
    - 'B'
  names_verbose:  # object names, customizable - USER DEFINED
    A: 'Origin'
    B: 'Target'
  row:            # number of grid rows, [#] - USER DEFINED
    A: 0
    B: 0
  col:            # number of grid columns, [#] - USER DEFINED
    A: 0
    B: 0
  row_pitch:      # distance between adjacent rows [mm] - USER DEFINED
    A: 0
    B: 0
  col_pitch:      # distance between adjacent columns [mm] - USER DEFINED
    A: 0
    B: 0
  x0:             # grid corner, referred to Eva frame's origin - x coordinate [mm] - USER DEFINED
    A: 0
    B: 0
  y0:             # grid corner, referred to Eva frame's origin - y coordinate [mm] - USER DEFINED
    A: 0
    B: 0
  angle:          # grid orientation, referred to Eva frame's origin [deg] - USER DEFINED
    A: 0
    B: 0
  angle_pickup:   # additional pick-up angle, [deg] - USER DEFINED
    A: 0
    B: 0
  surface:        # surf height of grid, referred to Eva frame's xy plane, [mm] - USER DEFINED
    A: 0
    B: 0
  object:         # object thickness, referred to Eva frame's z-axis, [mm] - USER DEFINED
    A: 0
    B: 0
  guess:
    A:            # joints guess for origin grid [rad] - USER DEFINED
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0
    B:            # joints guess for target grid [rad] - USER DEFINED
      - 0
      - 0
      - 0
      - 0
      - 0
      - 0